### ISSUE TITLE
Missing function in env() example.

### ISSUE THREAD

**Issue by netcarver** [modess/deploying-php-applications#14]
Hello, thanks for the book - purchased on Leanpub.

Just looking at the `env()` example in chapter 3 and think there's either a missing function `value()` or an error here: https://github.com/modess/deploying-php-applications/blob/4482ee350053aee1190d70226052169dc23806c4/manuscript/code/chapter-3/env-function.php#L6

**Comment by modess** [comment]
Thank you! I've created a fix for it and will be merging and pushing it to Leanpub.
