### ISSUE TITLE
Refusing to update checked out branch

### ISSUE THREAD

**Issue by jrean** [modess/deploying-php-applications#3]
Hi,

I bought your book (and just discovered it's now open source). Thank you for the awesome work!

Following your instruction I created a repository on my remote server.
After `git init` I created the `post-receive` hook file and added the following line:

```
#!/bin/bash
cd..
unset GIT_DIR

env -i git reset --hard
git checkout -f
```

I added the remote to my local git and performed a `git push production master` command to push...

Here is the output I received:

```
Counting objects: 781, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (720/720), done.
Writing objects: 100% (781/781), 32.39 MiB | 652.00 KiB/s, done.
Total 781 (delta 283), reused 0 (delta 0)
remote: error: refusing to update checked out branch: refs/heads/master
remote: error: By default, updating the current branch in a non-bare repository
remote: error: is denied, because it will make the index and work tree inconsistent
remote: error: with what you pushed, and will require 'git reset --hard' to match
remote: error: the work tree to HEAD.
remote: error:
remote: error: You can set 'receive.denyCurrentBranch' configuration variable to
remote: error: 'ignore' or 'warn' in the remote repository to allow pushing into
remote: error: its current branch; however, this is not recommended unless you
remote: error: arranged to update its work tree to match what you pushed in some
remote: error: other way.
remote: error:
remote: error: To squelch this message and still keep the default behaviour, set
remote: error: 'receive.denyCurrentBranch' configuration variable to 'refuse'.
To ssh://xxx/var/www/xxx/
 ! [remote rejected] master -> master (branch is currently checked out)
error: failed to push some refs to 'ssh://xxx/var/www/xxx/'
```

Questions:
- What's wrong?
- I used to do the same kind of flow but instead using a `git init --bare` repository.
- What's the difference between the two repository (as I have a hard time to clearly understand while googling)

Last but not least, I have your e-mail. I have some questions I would like to discuss with you. Can I send?

Thanks for your help.

Great job again.

J.

**Comment by jrean** [comment]
http://stackoverflow.com/questions/11117823/git-push-error-refusing-to-update-checked-out-branch

It says (in the comment):

>  in the latest git versions it is possible to push to a non-bare repository. Although possible, pushing to non-bare repositories is not common.

Cavit, when I performed `sudo apt-get install git` it installed git 2.7.4
So to get the latest I found:

```
sudo add-apt-repository ppa:git-core/ppa  
sudo apt-get update  
sudo apt-get install git
```

The version is now `2.8.3`

But it still doesn't work, I can't push to the remote repository.
It seems we can't push to the checked out branch of a non-bare repository.

I'm confused.

What do you think?

**Comment by jrean** [comment]
Also, in the book you metion:
`git remote add production <user>@<yourhost>:/var/www/app.git/`

If one use a custom `:port` it seems it won't work.

`git remote add production <user>@<yourhost>:port:/var/www/app.git/`

Should be:

`git remote add production <user>@<yourhost>:port/var/www/app.git/`

**Comment by modess** [comment]
Hello and thank you for your kind words!

About your issue in pushing to a bare Git repository, I must say that I'm not an expert in Git. I'm sure that the people on Stackoverflow have a lot more expertise in that area than I do. The things I know about is incorporating a Git workflow as a deployment process (as described in the book). This is not a reply to ignore your question and I hope you do not take it as that, I just think that you will get better help on Stackoverflow or somewhere else by Git experts :)

I will take a look at the port issue and update the book accordingly, thanks for catching that. I'll also reply to your e-mail.
